### ISSUE TITLE
Segfaults while handling CTRL-C

### ISSUE THREAD

**Issue by GnaneshKunal** [yolossn/lazykubernetes#5]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0x10e6f15]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0001020b0, 0x0, 0xc000079e38, 0xc000000208, 0xc000079e20, 0xc0000002b8)
	/Users/monster/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200201013258-57fdcf23edc5/gui.go:816 +0xb5
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0001020b0, 0xc000079e38, 0x2, 0x0)
	/Users/monster/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200201013258-57fdcf23edc5/gui.go:762 +0x28d
github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/Users/monster/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200201013258-57fdcf23edc5/gui.go:485
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0001020b0, 0xc0001020b0, 0x0)
	/Users/monster/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200201013258-57fdcf23edc5/gui.go:445 +0x20a
github.com/yolossn/lazykubernetes/pkg/gui.(*Gui).Run(0xc00000e038, 0x0, 0x0)
	/Users/monster/self/lazykubernetes/pkg/gui/gui.go:45 +0x1b0
github.com/yolossn/lazykubernetes/pkg/app.(*App).Run(...)
	/Users/monster/self/lazykubernetes/pkg/app/app.go:12
main.main()
	/Users/monster/self/lazykubernetes/main.go:11 +0x52
exit status 2

```

https://github.com/yolossn/lazykubernetes/pull/3#pullrequestreview-487204907

**Comment by yolossn** [comment]
@GnaneshKunal @nityanandagohain  I am planning to create a minor release where we fix all the known bugs. Please list all the known issue here.
- [x] SegFault on start (nil cluster-info View)
- [x] Out of range error (help me reproduce this ? @GnaneshKunal )
